### ISSUE TITLE
How to run OSLO Enterprise Architect UML Extractor?

### ISSUE THREAD

**Issue by cristianvasquez** [Informatievlaanderen/OSLO-UML-Transformer#52]
#### Issue type:

- :bug: Bug 

____
#### Description:

Hi, I'm trying to run oslo-extractor-uml-ea as standalone, using the [readme file](https://github.com/Informatievlaanderen/OSLO-UML-Transformer/tree/main/packages/oslo-extractor-uml-ea
) as reference but it fails to run

____
#### Crash log:

Error: Cannot find module '@oslo-extractor-uml-ea/DataRegistry'

**Comment by KristofVDB1** [comment]
Thanks for opening the issue @cristianvasquez ! I'll look into this today

**Comment by KristofVDB1** [comment]
The issue has been resolved. It was related to something we did not cover for one of our installed libraries, being . [`module-alias`](https://github.com/ilearnio/module-alias?tab=readme-ov-file#using-within-another-npm-package).

Please upgrade your version of `@oslo-flanders/ea-uml-extractor` to `0.0.17-alpha.0` or higher. 

The code below worked for me
```js
const { DataRegistry } = require("@oslo-flanders/ea-uml-extractor");

const extractModel = async () => {
    const model = new DataRegistry();
    await model.extract("link/to/eap.eap");
    console.log(model);
}

extractModel();
```

If this issue persists, feel free to reopen this issue.
